import React, { Component } from 'react';
import AppBar from '@material-ui/core/AppBar';
import Toolbar from '@material-ui/core/Toolbar';
import Typography from '@material-ui/core/Typography';
import Button from '@material-ui/core/Button';
import Menu from '@material-ui/core/Menu';
import MenuItem from '@material-ui/core/MenuItem';
import IconButton from '@material-ui/core/IconButton';
import { createStyles, WithStyles, withStyles } from "@material-ui/core/styles";
import MailIcon from '@material-ui/icons/Mail';
import { Theme } from "@material-ui/core/styles/createMuiTheme";
import loadable from '@loadable/component';
import NotificationsIcon from '@material-ui/icons/Notifications';
import { Badge } from '@material-ui/core';
import AccountCircle from '@material-ui/icons/AccountCircle';
import MoreIcon from '@material-ui/icons/MoreVert';
import Paper from '@material-ui/core/Paper';
import List from '@material-ui/core/List';
import ListSubheader from '@material-ui/core/ListSubheader';
import ListItem from '@material-ui/core/ListItem';
import ListItemAvatar from '@material-ui/core/ListItemAvatar';
import ListItemText from '@material-ui/core/ListItemText';
import CloseIcon from '@material-ui/icons/Close';
import Grid from '@material-ui/core/Grid';

const messages = [
  {
    id: 1,
    primary: 'Brunch this week?',
    secondary: "I'll be in the neighbourhood this week. Let's grab a bite to eat",
    date: "today"
  },
  {
    id: 2,
    primary: 'Birthday Gift',
    secondary: `Do you have a suggestion for a good present for John on his work
      anniversary. I am really confused & would love your thoughts on it.`,
  },
  {
    id: 3,
    primary: 'Recipe to try',
    secondary: 'I am try out this new BBQ recipe, I think this might be amazing',
  },
  {
    id: 4,
    primary: 'Yes!',
    secondary: 'I have the tickets to the ReactConf for this year.',
    date: "2020/03/24"
  },
  {
    id: 5,
    primary: "Doctor's Appointment",
    secondary: 'My appointment for the doctor was rescheduled for next Saturday.',
  },
  {
    id: 6,
    primary: 'Discussion',
    secondary: `Menus that are generated by the bottom app bar (such as a bottom
      navigation drawer or overflow menu) open as bottom sheets at a higher elevation
      than the bar.`,
  },
  {
    id: 7,
    primary: 'Summer BBQ',
    secondary: `Who wants to have a cookout this weekend? I just got some furniture
      for my backyard and would love to fire up the grill.`,
  },
];

const styles = (theme: Theme) =>
    createStyles({
        root: {
            flexGrow: 1
        },
        loginTitle : {
          textAlign: "center",
          flexGrow: 1,
        },
        title: {
          flexGrow: 1,
        },
        sectionDesktop: {
          display: 'none',
          [theme.breakpoints.up('md')]: {
            display: 'flex',
          },
        },
        sectionMobile: {
          display: 'flex',
          [theme.breakpoints.up('md')]: {
            display: 'none',
          },
        },
        text: {
          padding: theme.spacing(2, 2, 0),
        },
        paper: {
          paddingBottom: 50,
        },
        list: {
          marginBottom: theme.spacing(1),
        },
        subheader: {
          backgroundColor: theme.palette.background.paper,
        },
        closeIcon: {
          textAlign: "right",
          paddingLeft: 390
        }
    });
export interface State {
  anchorEl:any
  anchorEl2:any
  mobileMoreAnchorEl:any
}   

export interface AppbarProps extends WithStyles<typeof styles> {
  isLogin?: boolean,
  isLoginPage?: boolean,
  title?: string,
  session?: any
}

function titleDiv(title?: string){
    return <div>
    {title}
  </div>
}

class Appbar extends Component<AppbarProps> {

  state:State = {
    anchorEl:null,
    anchorEl2:null,
    mobileMoreAnchorEl:null
  }

  render() {
    const {classes, title, isLogin, isLoginPage, session} = this.props;
    const logout = () => {
      let jsonData = {
        method: 'POST',
        headers: {
            'Accept': 'application/json',
            'Content-Type': 'application/json'
        },
        body: null};
        fetch('/logout', jsonData)
        .then(res => {
          res.json().then(
            data => {
              window.location.replace("/login");
            }
          )
        })
        .then(json => console.log(json))
        .catch(err => console.log(err));
    };
    const menuId = 'primary-search-account-menu';
    const menu2Id = 'primary-search-account-menu';
    const isMenuOpen = Boolean(this.state.anchorEl);
    const isMenu2Open = Boolean(this.state.anchorEl2);
    

    const mobileMenuId = 'primary-search-account-menu-mobile';
    
    const handleProfileMenuOpen = (event: any) => {
      setAnchorEl(event.currentTarget);
    };
    const handleProfileMenuClose = () => {
      setAnchorEl(null);
      handleMobileMenuClose();
    };
    const handleMobileMenuOpen = (event: any) => {
      setMobileMoreAnchorEl(event.currentTarget);
    };
    const handleMobileMenuClose = () => {
      setMobileMoreAnchorEl(null);
    };
    const eventMessageListOpen = (event: any) => {
      setAnchor2El(event.currentTarget);
    }
    const eventMessageListclose = () => {
      setAnchor2El(null);
    }
    
    
    const setAnchorEl = (target:EventTarget & HTMLButtonElement | null) => {
      this.setState({
        anchorEl: target
      })
    }

    const setAnchor2El = (target:EventTarget & HTMLButtonElement | null) => {
      this.setState({
        anchorEl2: target
      })
    }

    const setMobileMoreAnchorEl = (target:EventTarget & HTMLButtonElement | null) => {
      this.setState({
        mobileMoreAnchorEl: target
      })
    }
    const isMobileMenuOpen = Boolean(this.state.mobileMoreAnchorEl);
    const renderMenu = (
      <Menu
        anchorEl={this.state.anchorEl}
        anchorOrigin={{ vertical: 'top', horizontal: 'right' }}
        id={menuId}
        keepMounted
        transformOrigin={{ vertical: 'top', horizontal: 'right' }}
        open={isMenuOpen}
        onClose={handleProfileMenuClose}
      >
        <MenuItem onClick={handleProfileMenuClose}>Profile</MenuItem>
        <MenuItem onClick={handleProfileMenuClose}>My account</MenuItem>
      </Menu>
    );
    let counter:number = 0;
    const eventMessageList = (
    <Menu
        anchorEl={this.state.anchorEl2}
        anchorOrigin={{ vertical: 'top', horizontal: 'right' }}
        id={menu2Id}
        keepMounted
        transformOrigin={{ vertical: 'top', horizontal: 'right' }}
        open={isMenu2Open}
        onClose={eventMessageListclose}
      >
        <Paper square className={classes.paper}>
        
          <Typography className={classes.text} variant="h5" gutterBottom>Event Message Box
            <IconButton aria-label="delete" color="primary" className={classes.closeIcon} onClick={eventMessageListclose}  >
              <CloseIcon className={classes.closeIcon} />
            </IconButton>  
          </Typography>
          
              
          
          
          <List className={classes.list}>
            {messages.map(({ id, primary, secondary, date}) => (
              <React.Fragment key={id}>
                {date != null  && <ListSubheader className={classes.subheader}>{date}</ListSubheader>}
                <ListItem button>
                  <ListItemText primary={primary} secondary={secondary} />
                </ListItem>
              </React.Fragment>
            ))}
          </List>
        </Paper>
      </Menu>
    );

    const renderMobileMenu = (
      <Menu
        anchorEl={this.state.mobileMoreAnchorEl}
        anchorOrigin={{ vertical: 'top', horizontal: 'right' }}
        id={mobileMenuId}
        keepMounted
        transformOrigin={{ vertical: 'top', horizontal: 'right' }}
        open={isMobileMenuOpen}
        onClose={handleMobileMenuClose}
      >
        <MenuItem onClick={eventMessageListOpen}>
          <IconButton 
          aria-label="show 17 new notifications"
          color="inherit" 
          aria-controls={menu2Id}
          aria-haspopup="true"
          >
            <Badge badgeContent={11} color="secondary">
              <NotificationsIcon />
            </Badge>
          </IconButton>
          <p>Notifications</p>
        </MenuItem>
        <MenuItem onClick={handleProfileMenuOpen}>
          <IconButton
            aria-label="account of current user"
            aria-controls="primary-search-account-menu"
            aria-haspopup="true"
            color="inherit"
          >
            <AccountCircle />
          </IconButton>
          <p>Profile</p>
        </MenuItem>
      </Menu>
    );
    
    
    let content: any = null;
    if (!isLoginPage) {
      content = <div className={classes.root}>
      <AppBar position="static">
        <Toolbar  >
          <Typography variant="h6" className={classes.title}>
            {titleDiv(title)}
          </Typography>
          <div className={classes.sectionDesktop}>
            <IconButton 
              aria-label="show 17 new notifications"
              color="inherit" 
              onClick={eventMessageListOpen}
              edge="end"
              aria-controls={menu2Id}
              aria-haspopup="true"
              >
              <Badge badgeContent={17} color="secondary">
                <NotificationsIcon />
              </Badge>
            </IconButton>
            <IconButton
              edge="end"
              aria-label="account of current user"
              aria-controls={menuId}
              aria-haspopup="true"
              
              color="inherit"
              onClick={handleProfileMenuOpen}
            >
              <AccountCircle />
            </IconButton>
          </div>
          <div className={classes.sectionMobile}>
            <IconButton
              aria-label="show more"
              aria-controls={mobileMenuId}
              aria-haspopup="true"
              onClick={handleMobileMenuOpen}
              color="inherit"
            >
              <MoreIcon />
            </IconButton>
          </div>
            <Button color="inherit" onClick={logout} >Log Out</Button>
        </Toolbar>
      </AppBar>
      
      
    </div>;
    } else {
      content = <div className={classes.root}>
      <AppBar position="static" style={{ background: '#03a9f4'}} >
        <Toolbar>
          <IconButton edge="start"  color="default" aria-label="menu">
          </IconButton>
          <Typography variant="h6" className={classes.loginTitle}>
            {titleDiv(title)}
          </Typography>
        </Toolbar>
      </AppBar>
    </div>;
    }
    return (
      <div>
        {content}
        {eventMessageList}
        {renderMobileMenu}
        {renderMenu}
      </div>
    );
  }
}

export default withStyles(styles)(Appbar);